### ISSUE TITLE
Disabled commands should be disabled in the commands guide

### ISSUE THREAD

**Issue by lkcampbell** [peterflynn/brackets-commands-guide#1]
Repro Steps:
(1) Open a document and make sure there are no JSLint errors in it.
(2) Open Navigate menu and make sure Go to First JSLint Error is disabled.
(3) Open the Commands Guide and type 'g'.

Observed Behavior:
Go to First JSLint Error appears to be enabled.  I can click it but nothing happens.

Expected Behavior:
Go to First JSLint Error appears to be disabled.  I should not be able to click it.

**Comment by artoale** [comment]
:+1: (btw, the keybinding on Mac is really inconvenient)

**Comment by DreadfulBaguette** [comment]
@artoale I'm not actually affiliated with this extension at all, but I wanted to point out that you can change the keybinding in brackets. Just open up the keymap.json file and add something like `"Ctrl-Shift-P" : "pflynn.searchCommands",` to the overrides section. That will allow you to map it to a different key.
